/** P13: fake Quadlet unit files (podman-systemd.unit(5) INI syntax). */
import { quadletService } from './trees.ts';

export function quadletIni(file: string): string[] {
  const [base, type] = file.split('.');
  const head = ['[Unit]', `Description=${base} ${type} (managed by Quadlet)`];
  const install = ['', '[Install]', 'WantedBy=default.target'];
  switch (type) {
    case 'container':
      return [
        '# Generated by Podman Desktop · Podman Quadlet extension',
        ...head,
        ...(base.endsWith('db') ? [] : ['After=orders-db.service', 'Requires=orders-db.service']),
        '',
        '[Container]',
        `ContainerName=${base}`,
        `Image=${base.endsWith('db') ? 'registry.redhat.io/rhel10/postgresql-16:latest' : base === 'backup' ? 'quay.io/acme/backup:2.0' : 'quay.io/acme/orders-api:1.4'}`,
        `PublishPort=${base.endsWith('db') ? '5432:5432' : '8080:8080'}`,
        `Volume=orders-data.volume:/var/lib/data:Z`,
        'Network=orders.network',
        `Environment=APP_PROFILE=prod`,
        `Environment=DB_URL=postgresql://orders-db:5432/orders`,
        'AutoUpdate=registry',
        'HealthCmd=curl -fs http://localhost:8080/q/health',
        '',
        '[Service]',
        'Restart=always',
        'TimeoutStartSec=900',
        ...install,
      ];
    case 'pod':
      return [...head, '', '[Pod]', `PodName=${base}`, 'PublishPort=8080:8080', 'Network=orders.network', ...install];
    case 'kube':
      return [...head, '', '[Kube]', `Yaml=/home/dev/.config/containers/systemd/${base}.yaml`, 'PublishPort=9090:8080', 'AutoUpdate=registry', '', '[Service]', 'Restart=on-failure', ...install];
    case 'volume':
      return [...head, '', '[Volume]', `VolumeName=${base}`, 'Label=app=orders', 'Driver=local'];
    case 'network':
      return [...head, '', '[Network]', `NetworkName=${base}`, 'Subnet=10.89.10.0/24', 'Gateway=10.89.10.1', 'DNS=10.89.10.1'];
    case 'image':
      return [...head, '', '[Image]', 'Image=quay.io/acme/orders-api:1.4', 'AuthFile=/run/user/1000/containers/auth.json'];
    default:
      return head;
  }
}

export function systemctlStatus(file: string, status: string): string[] {
  const svc = quadletService(file);
  const up = status === 'running';
  return [
    `● ${svc} - ${file.split('.')[0]} ${file.split('.')[1]} (managed by Quadlet)`,
    `     Loaded: loaded (/home/dev/.config/containers/systemd/${file}; generated)`,
    `     Active: ${up ? 'active (running) since Thu 2026-10-09 09:12:01 CEST; 2h 14min ago' : status === 'ready' ? 'active (exited) since Thu 2026-10-09 09:11:58 CEST' : 'inactive (dead)'}`,
    ...(up ? [`   Main PID: 4410 (conmon)`, '      Tasks: 23 (limit: 18837)', '     Memory: 212.4M', '        CPU: 41.233s'] : []),
  ];
}
