/**
 * P13: extension tree providers. An extension contributes its own sub-tree to
 * a connection (root → children → grandchildren), rendered in the left tree;
 * clicking a node opens it in a tab (`{ kind: 'node', nodeId }`).
 */
import {
  faBook,
  faBookOpen,
  faCodeCompare,
  faBoxArchive,
  faCircleInfo,
  faClockRotateLeft,
  faComments,
  faCube,
  faFileCode,
  faFileLines,
  faHardDrive,
  faMessage,
  faServer,
  faWrench,
} from '@fortawesome/free-solid-svg-icons';
import { ContainerIcon } from '@podman-desktop/ui-svelte/icons';

import type { IconRef } from '#lib/ext/types.ts';
import ImageIcon from '#lib/images/ImageIcon.svelte';
import NetworkIcon from '#lib/images/NetworkIcon.svelte';
import PodIcon from '#lib/images/PodIcon.svelte';
import VolumeIcon from '#lib/images/VolumeIcon.svelte';

import { altFor, HB_ALTS, HB_CATALOG, HB_CONN } from './hb-data.ts';

/**
 * Icon rule: an extension root uses the extension logo; every child uses a
 * semantic icon (the core resource icon when it is one: Images, Pods…).
 * Every dashboard / overview, in the tree and in tabs, uses `OVERVIEW_ICON`.
 */
export const OVERVIEW_ICON: IconRef = faCircleInfo;

const overview = (detail = ''): Raw => ({ label: 'Overview', icon: OVERVIEW_ICON, detail });

export interface TreeNode {
  id: string;
  label: string;
  icon?: IconRef;
  status?: string;
  /** Dim text after the label. */
  detail?: string;
  /** Extra fields (quadlet type, service, path…). */
  data?: Record<string, string>;
  children?: TreeNode[];
}

export interface TreeProvider {
  id: string;
  /** Extension providing the tree (see `r3/exts.ts`). */
  extId: string;
  label: string;
  /** Extension logo (root icon). */
  icon: string;
  /** Connections the tree is contributed to. */
  connIds: string[];
  /** Flat sections of the dataset the tree replaces in P13. */
  replaces: string[];
  build: (connId: string) => Raw[];
}

export type Raw = Omit<TreeNode, 'id' | 'children'> & { children?: Raw[] };

/** name, tools, resources, prompts, transport, clients, image / command. */
const MCP_SERVERS: [string, string[], string[], string[], string, string, string][] = [
  ['github', ['list_issues', 'create_pull_request', 'get_file_contents', 'search_code'], ['repo://acme/orders'], ['review-pr'], 'stdio', 'Claude Code, Goose', 'ghcr.io/github/github-mcp-server:0.9'],
  ['kubernetes', ['pods_list', 'pods_log', 'resources_get', 'events_list'], ['kubeconfig://current'], [], 'SSE', 'Claude Code', 'quay.io/containers/kubernetes-mcp-server:0.4'],
  ['podman', ['container_list', 'container_run', 'image_pull'], [], ['debug-container'], 'stdio', 'Claude Code, VS Code', 'podman-mcp-server --socket podman.sock'],
  ['filesystem', ['read_file', 'write_file', 'list_directory'], ['file:///home/dev/orders'], [], 'stdio', '—', 'docker.io/mcp/filesystem:latest'],
  ['postgres', ['query', 'list_tables'], ['postgres://orders-db/orders'], ['explain-query'], 'Streamable HTTP', 'Goose', 'docker.io/mcp/postgres:latest'],
];

const mcp = (): Raw[] => [
  overview(),
  ...MCP_SERVERS.map(([name, tools, resources, prompts, transport, clients, command], i) => ({
    label: name,
    icon: faServer,
    status: i === 3 ? 'stopped' : 'running',
    detail: `${tools.length} tools`,
    data: { transport, clients, command, tools: String(tools.length) },
    children: [
      { label: 'Tools', icon: faWrench, detail: String(tools.length), children: tools.map(t => ({ label: t, icon: faWrench })) },
      { label: 'Resources', icon: faFileLines, detail: String(resources.length), children: resources.map(r => ({ label: r, icon: faFileLines })) },
      { label: 'Prompts', icon: faMessage, detail: String(prompts.length), children: prompts.map(p => ({ label: p, icon: faMessage })) },
    ],
  })),
];

const HELM: [string, string, number][] = [
  ['kafka-ui', 'kafka-ui-0.7.6', 3],
  ['grafana', 'grafana-8.5.2', 2],
  ['postgres', 'postgresql-16.0.1', 4],
  ['keycloak', 'keycloak-24.1.0', 1],
];

const helm = (connId: string): Raw[] =>
  HELM.slice(0, connId === 'kind-dev' ? 2 : 4).map(([name, chart, revs]) => ({
    label: name,
    icon: faBoxArchive,
    status: 'running',
    detail: chart,
    data: { chart, revision: String(revs), namespace: name === 'keycloak' ? 'auth' : 'default', updated: `${revs + 1} days ago` },
    children: Array.from({ length: revs }, (_, i) => ({
      label: `Revision ${revs - i}`,
      icon: faClockRotateLeft,
      detail: i === 0 ? 'deployed' : 'superseded',
    })),
  }));

const QUADLETS: [string, string][] = [
  ['orders-api.container', 'running'],
  ['orders-db.container', 'running'],
  ['orders.pod', 'running'],
  ['checkout.kube', 'running'],
  ['backup.container', 'stopped'],
  ['orders-data.volume', 'ready'],
  ['orders.network', 'ready'],
  ['orders-api.image', 'ready'],
];

/** systemd service generated by Quadlet for a unit file (podman-systemd.unit(5)). */
export function quadletService(file: string): string {
  const [base, type] = file.split('.');
  return type === 'container' || type === 'kube' ? `${base}.service` : `${base}-${type}.service`;
}

const QUADLET_ICON: Record<string, IconRef> = { container: ContainerIcon, pod: PodIcon, kube: faFileCode, volume: VolumeIcon, network: NetworkIcon, image: ImageIcon };

const quadlets = (): Raw[] =>
  QUADLETS.map(([name, status]) => ({
    label: name,
    icon: QUADLET_ICON[name.split('.')[1]] ?? faFileCode,
    status,
    detail: quadletService(name),
    data: { type: `.${name.split('.')[1]}`, service: quadletService(name), path: `~/.config/containers/systemd/${name}` },
  }));

const aiLab = (): Raw[] => [
  overview(),
  {
    label: 'Models',
    icon: faCube,
    detail: '3',
    children: [
      { label: 'granite-3.3-8b-instruct', icon: faCube, detail: '4.9 GB' },
      { label: 'mistral-7b-instruct-v0.3', icon: faCube, detail: '4.1 GB' },
      { label: 'whisper-small', icon: faCube, detail: '466 MB' },
    ],
  },
  {
    label: 'Services',
    icon: faServer,
    detail: '2',
    children: [
      { label: 'granite inference', icon: faServer, status: 'running', detail: ':35000' },
      { label: 'whisper inference', icon: faServer, status: 'stopped', detail: ':35001' },
    ],
  },
  {
    label: 'Playgrounds',
    icon: faComments,
    detail: '2',
    children: [
      { label: 'RAG over orders docs', icon: faComments, detail: 'granite' },
      { label: 'Prompt tuning', icon: faComments, detail: 'mistral' },
    ],
  },
];

const bootc = (): Raw[] => [
  overview(),
  { label: 'Images', icon: ImageIcon, detail: '3' },
  { label: 'Disk Images', icon: faHardDrive, detail: '2' },
  { label: 'Examples', icon: faBook, detail: '6' },
];

/** Hummingbird (Red Hat Hardened Images): Overview, Catalog (hardened images), Alternatives (local images). */
const hummingbird = (): Raw[] => [
  overview(),
  {
    label: 'Catalog',
    icon: faBookOpen,
    detail: String(HB_CATALOG.length),
    children: HB_CATALOG.map(h => ({ label: `hummingbird/${h.name}`, icon: ImageIcon, detail: h.tags[0], data: { hb: h.name } })),
  },
  {
    label: 'Alternatives',
    icon: faCodeCompare,
    detail: String(HB_ALTS.length),
    children: HB_ALTS.map(a => ({ label: a.local, icon: ImageIcon, detail: `→ ${altFor(a.local)?.hb}`, data: { local: a.local } })),
  },
];

export const TREE_PROVIDERS: TreeProvider[] = [
  { id: 'bootc', extId: 'bootc', label: 'Bootable containers', icon: 'icons/redhat.bootc.png', connIds: ['podman-machine-default'], replaces: ['bootc'], build: bootc },
  { id: 'quadlets', extId: 'quadlet', label: 'Quadlets', icon: 'icons/podman-desktop.quadlet.png', connIds: ['podman-machine-default'], replaces: ['quadlets'], build: quadlets },
  { id: 'ai-lab', extId: 'ai-lab', label: 'AI Lab', icon: 'icons/redhat.ai-lab.png', connIds: ['podman-machine-default'], replaces: [], build: aiLab },
  { id: 'mcp', extId: 'mcp', label: 'MCP servers', icon: 'icons/podman-desktop.mcp.png', connIds: ['podman-machine-default', 'mcp-gateway'], replaces: ['mcpservers', 'mcptools'], build: mcp },
  { id: 'hummingbird', extId: 'hummingbird', label: 'Hummingbird', icon: 'icons/redhat.hummingbird.png', connIds: [HB_CONN], replaces: [], build: hummingbird },
  { id: 'helm', extId: 'helm', label: 'Helm releases', icon: 'icons/podman-desktop.helm.png', connIds: ['kind-dev', 'openshift-local', 'ocp-dev', 'ocp-prod'], replaces: ['helm'], build: helm },
];

function withIds(prefix: string, raw: Raw[]): TreeNode[] {
  return raw.map(r => {
    const id = `${prefix}/${r.label}`;
    return { ...r, id, children: r.children ? withIds(id, r.children) : undefined };
  });
}

const cache = new Map<string, TreeNode>();

/** Root node of a provider for a connection (children have stable ids). */
export function treeRoot(p: TreeProvider, connId: string): TreeNode {
  const key = `${p.id}@${connId}`;
  let root = cache.get(key);
  if (!root) {
    const children = withIds(key, p.build(connId));
    root = { id: key, label: p.label, icon: p.icon, detail: String(children.filter(x => x.label !== 'Overview').length), children };
    cache.set(key, root);
  }
  return root;
}

export interface FoundNode {
  node: TreeNode;
  root: TreeNode;
  provider: TreeProvider;
  connId: string;
  /** Labels of the ancestors (root first). */
  path: string[];
}

export function findNode(id: string | undefined): FoundNode | undefined {
  if (!id) return undefined;
  const [key] = id.split('/');
  const [pid, connId] = key.split('@');
  const provider = TREE_PROVIDERS.find(p => p.id === pid);
  if (!provider || !connId) return undefined;
  const root = treeRoot(provider, connId);
  const walk = (n: TreeNode, path: string[]): FoundNode | undefined => {
    if (n.id === id) return { node: n, root, provider, connId, path };
    for (const ch of n.children ?? []) {
      const f = walk(ch, [...path, n.label]);
      if (f) return f;
    }
    return undefined;
  };
  return walk(root, []);
}
